# Generated by Django 4.2 on 2025-10-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id_equipement', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('AUTORISE', 'Autorisé'), ('INTERDIT', 'Interdit'), ('SOUMIS', 'Soumis à autorisation')], default='AUTORISE', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
