# Generated by Django 4.2 on 2025-10-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_dequipement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipements/'),
        ),
    ]
