# Generated by Django 4.2 on 2025-10-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_dequipement', '0002_equipement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
