# Generated by Django 4.2 on 2025-10-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_dequipement', '0003_equipement_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='phash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
