# Generated by Django 5.2.7 on 2025-10-28 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='The subject or title of the report.', max_length=255)),
                ('body', models.TextField(help_text='The main content of the report. Must be at least 500 characters.')),
                ('department', models.CharField(choices=[('security', 'Security Department'), ('immigration', 'Immigration Department'), ('civil_protection', 'Civil Protection'), ('finance', 'Finance Department'), ('planning', 'Planning and Development')], help_text='Select the department associated with this report.', max_length=50)),
                ('bibliographies', models.JSONField(default=list, help_text='List of information sources or reference links.')),
                ('used_documents', models.JSONField(default=list, help_text='List of used or referenced document names or file paths.')),
                ('categories', models.JSONField(default=list, help_text='List of tags or topics (must be from predefined categories).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
