# Generated by Django 4.2 on 2025-10-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id_camera', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la caméra')),
                ('zone', models.CharField(max_length=255, verbose_name='Zone')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('resolution', models.CharField(default='1080p', max_length=50, verbose_name='Résolution')),
                ('status', models.CharField(choices=[('RECORDING', 'Recording'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], default='RECORDING', max_length=20, verbose_name='Statut')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Caméra',
                'verbose_name_plural': 'Caméras',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
