# Generated by Django 5.2.7 on 2025-10-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='nearby_places',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='zone',
            name='zone_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
