# Generated by Django 5.2.7 on 2025-10-31 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones_app', '0002_zone_nearby_places_zone_zone_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zonealert',
            options={'ordering': ['-detected_at'], 'verbose_name': 'Zone Alert', 'verbose_name_plural': 'Zone Alerts'},
        ),
        migrations.AddField(
            model_name='zonealert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonealert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['-created_at'], name='zones_app_z_created_9d5dec_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['status'], name='zones_app_z_status_58e1bc_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['zone_type'], name='zones_app_z_zone_ty_a0d72a_idx'),
        ),
        migrations.AddIndex(
            model_name='zonealert',
            index=models.Index(fields=['-detected_at'], name='zones_app_z_detecte_149506_idx'),
        ),
        migrations.AddIndex(
            model_name='zonealert',
            index=models.Index(fields=['severity'], name='zones_app_z_severit_37f541_idx'),
        ),
        migrations.AddIndex(
            model_name='zonealert',
            index=models.Index(fields=['is_resolved'], name='zones_app_z_is_reso_a3c0f2_idx'),
        ),
    ]
